<!DOCTYPE html>
<html lang="en-us"> 
	<head>
		<meta charset="utf-8">	
	</head>
	<body>
		
	<!-- Script 1.2 - first.php -->
	<p>This is standard HTML.</p>
	<?php
		echo 'This is generated by PHP!';
	?>
	</body>
</html>